CREATE TABLE IF NOT EXISTS MST_USER (
    USER_ID      VARCHAR(50)   NOT NULL,
    PASSWORD     VARCHAR(100)  NOT NULL,
    DISPLAY_NAME VARCHAR(100)  NOT NULL,
    ROLE         VARCHAR(30)   NOT NULL DEFAULT 'USER',
    USE_YN       CHAR(1)       NOT NULL DEFAULT 'Y',
    CREATED_AT   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID),
    INDEX idx_mst_user_role (ROLE)
);
