spring:
  flyway:
    enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mysql-hd-mes.j.aivencloud.com:10483/MES_DB?allowPublicKeyRetrieval=true&useSSL=true&trustServerCertificate=true&sslMode=trust
    username: avnadmin
    password: ${MES_DB_PASSWORD}

logging:
  level:
    root: INFO
    com.mes: INFO
    org.springframework.web: INFO
    com.mes.infra.persistence.mybatis.mapper: INFO
    # jdbc.resultsettable: DEBUG
