-- ============================================================
-- MES 시스템 데이터베이스 DDL 스크립트
-- DBMS: MariaDB 10.x
-- 파일: mes_ddl_04_inventory.sql (재고관리)
-- 작성일: 2025-01-19
-- ============================================================

USE MES_DB;

-- ------------------------------------------------------------
-- 7. 재고관리 테이블
-- ------------------------------------------------------------

-- 7.1 재고현황 (INV_STOCK)
CREATE TABLE INV_STOCK (
    STOCK_ID        BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '재고ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    WAREHOUSE_CD    VARCHAR(20)     NOT NULL    COMMENT '창고코드',
    LOCATION_CD     VARCHAR(50)     NULL        COMMENT '로케이션코드',
    ITEM_CD         VARCHAR(50)     NOT NULL    COMMENT '품목코드',
    LOT_NO          VARCHAR(50)     NULL        COMMENT 'LOT번호',
    STOCK_QTY       DECIMAL(15,3)   NOT NULL    DEFAULT 0 COMMENT '재고수량',
    RESERVED_QTY    DECIMAL(15,3)   NULL        DEFAULT 0 COMMENT '예약수량',
    AVAILABLE_QTY   DECIMAL(15,3)   GENERATED ALWAYS AS (STOCK_QTY - COALESCE(RESERVED_QTY, 0)) STORED COMMENT '가용수량',
    UNIT            VARCHAR(20)     NOT NULL    COMMENT '단위',
    STOCK_STATUS    VARCHAR(20)     NOT NULL    DEFAULT '정상' COMMENT '재고상태',
    LAST_IN_DT      DATE            NULL        COMMENT '최종입고일',
    LAST_OUT_DT     DATE            NULL        COMMENT '최종출고일',
    EXPIRE_DT       DATE            NULL        COMMENT '유효기한',
    MFG_DT          DATE            NULL        COMMENT '제조일자',
    UNIT_COST       DECIMAL(18,4)   NULL        COMMENT '단가',
    STOCK_AMT       DECIMAL(18,2)   NULL        COMMENT '재고금액',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (STOCK_ID),
    UNIQUE KEY UK_INV_STOCK (PLANT_CD, WAREHOUSE_CD, ITEM_CD, LOT_NO, LOCATION_CD),
    CONSTRAINT FK_INV_STOCK_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_INV_STOCK_WH FOREIGN KEY (WAREHOUSE_CD) REFERENCES MST_WAREHOUSE(WAREHOUSE_CD),
    CONSTRAINT FK_INV_STOCK_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='재고현황';

-- 7.2 입출고이력 (INV_TRANS_HIS)
CREATE TABLE INV_TRANS_HIS (
    TRANS_ID        BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '거래ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    TRANS_NO        VARCHAR(30)     NOT NULL    COMMENT '거래번호',
    TRANS_DT        DATE            NOT NULL    COMMENT '거래일자',
    TRANS_TYPE      VARCHAR(20)     NOT NULL    COMMENT '거래유형',
    TRANS_REASON    VARCHAR(50)     NOT NULL    COMMENT '거래사유',
    ITEM_CD         VARCHAR(50)     NOT NULL    COMMENT '품목코드',
    LOT_NO          VARCHAR(50)     NULL        COMMENT 'LOT번호',
    TRANS_QTY       DECIMAL(15,3)   NOT NULL    COMMENT '거래수량',
    UNIT            VARCHAR(20)     NOT NULL    COMMENT '단위',
    FROM_WAREHOUSE_CD VARCHAR(20)   NULL        COMMENT '출고창고코드',
    TO_WAREHOUSE_CD VARCHAR(20)     NULL        COMMENT '입고창고코드',
    FROM_LOCATION_CD VARCHAR(50)    NULL        COMMENT '출고로케이션',
    TO_LOCATION_CD  VARCHAR(50)     NULL        COMMENT '입고로케이션',
    BEFORE_QTY      DECIMAL(15,3)   NULL        COMMENT '변경전수량',
    AFTER_QTY       DECIMAL(15,3)   NULL        COMMENT '변경후수량',
    REF_TYPE        VARCHAR(20)     NULL        COMMENT '참조유형',
    REF_NO          VARCHAR(50)     NULL        COMMENT '참조번호',
    REF_ID          BIGINT          NULL        COMMENT '참조ID',
    VENDOR_CD       VARCHAR(50)     NULL        COMMENT '거래처코드',
    UNIT_PRICE      DECIMAL(18,4)   NULL        COMMENT '단가',
    TRANS_AMT       DECIMAL(18,2)   NULL        COMMENT '거래금액',
    TRANS_USER_ID   VARCHAR(20)     NULL        COMMENT '처리자ID',
    TRANS_RMK       VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (TRANS_ID),
    UNIQUE KEY UK_INV_TRANS_HIS (TRANS_NO),
    CONSTRAINT FK_INV_TRANS_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_INV_TRANS_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD),
    CONSTRAINT FK_INV_TRANS_FROM_WH FOREIGN KEY (FROM_WAREHOUSE_CD) REFERENCES MST_WAREHOUSE(WAREHOUSE_CD),
    CONSTRAINT FK_INV_TRANS_TO_WH FOREIGN KEY (TO_WAREHOUSE_CD) REFERENCES MST_WAREHOUSE(WAREHOUSE_CD),
    CONSTRAINT FK_INV_TRANS_VENDOR FOREIGN KEY (VENDOR_CD) REFERENCES MST_VENDOR(VENDOR_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='입출고이력';

-- 7.3 LOT정보 (INV_LOT)
CREATE TABLE INV_LOT (
    LOT_ID          BIGINT          NOT NULL    AUTO_INCREMENT COMMENT 'LOT ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    LOT_NO          VARCHAR(50)     NOT NULL    COMMENT 'LOT번호',
    ITEM_CD         VARCHAR(50)     NOT NULL    COMMENT '품목코드',
    LOT_QTY         DECIMAL(15,3)   NOT NULL    COMMENT 'LOT수량',
    CURRENT_QTY     DECIMAL(15,3)   NOT NULL    DEFAULT 0 COMMENT '현재수량',
    CREATE_DT       DATE            NOT NULL    COMMENT '생성일',
    MFG_DT          DATE            NULL        COMMENT '제조일',
    EXPIRE_DT       DATE            NULL        COMMENT '유효기한',
    VENDOR_CD       VARCHAR(50)     NULL        COMMENT '공급업체',
    VENDOR_LOT_NO   VARCHAR(50)     NULL        COMMENT '공급업체LOT',
    PARENT_LOT_NO   VARCHAR(50)     NULL        COMMENT '상위LOT번호',
    WO_ID           BIGINT          NULL        COMMENT '작업지시ID',
    LOT_TYPE        VARCHAR(20)     NOT NULL    DEFAULT '생산' COMMENT 'LOT유형',
    LOT_STATUS      VARCHAR(20)     NOT NULL    DEFAULT '정상' COMMENT 'LOT상태',
    INSPECT_STATUS  VARCHAR(20)     NULL        COMMENT '검사상태',
    LOT_GRADE       VARCHAR(20)     NULL        COMMENT 'LOT등급',
    LOT_RMK         VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (LOT_ID),
    UNIQUE KEY UK_INV_LOT (LOT_NO),
    CONSTRAINT FK_INV_LOT_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_INV_LOT_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD),
    CONSTRAINT FK_INV_LOT_VENDOR FOREIGN KEY (VENDOR_CD) REFERENCES MST_VENDOR(VENDOR_CD),
    CONSTRAINT FK_INV_LOT_WO FOREIGN KEY (WO_ID) REFERENCES PLN_WORK_ORDER(WO_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='LOT정보';

-- 7.4 LOT추적이력 (INV_LOT_TRACE)
CREATE TABLE INV_LOT_TRACE (
    TRACE_ID        BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '추적ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    LOT_NO          VARCHAR(50)     NOT NULL    COMMENT 'LOT번호',
    PARENT_LOT_NO   VARCHAR(50)     NULL        COMMENT '상위LOT번호',
    CHILD_LOT_NO    VARCHAR(50)     NULL        COMMENT '하위LOT번호',
    TRACE_TYPE      VARCHAR(20)     NOT NULL    COMMENT '추적유형',
    TRACE_LEVEL     INT             NOT NULL    DEFAULT 1 COMMENT '추적레벨',
    ITEM_CD         VARCHAR(50)     NOT NULL    COMMENT '품목코드',
    PROCESS_CD      VARCHAR(20)     NULL        COMMENT '공정코드',
    WO_ID           BIGINT          NULL        COMMENT '작업지시ID',
    RESULT_ID       BIGINT          NULL        COMMENT '작업실적ID',
    TRACE_DTM       DATETIME        NOT NULL    COMMENT '추적일시',
    TRACE_QTY       DECIMAL(15,3)   NULL        COMMENT '추적수량',
    TRACE_RMK       VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    PRIMARY KEY (TRACE_ID),
    CONSTRAINT FK_INV_LOT_TRACE_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_INV_LOT_TRACE_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD),
    CONSTRAINT FK_INV_LOT_TRACE_WO FOREIGN KEY (WO_ID) REFERENCES PLN_WORK_ORDER(WO_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='LOT추적이력';

-- 7.5 재고실사 (INV_STOCKTAKING)
CREATE TABLE INV_STOCKTAKING (
    STOCKTAKING_ID  BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '실사ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    STOCKTAKING_NO  VARCHAR(30)     NOT NULL    COMMENT '실사번호',
    STOCKTAKING_DT  DATE            NOT NULL    COMMENT '실사일자',
    WAREHOUSE_CD    VARCHAR(20)     NOT NULL    COMMENT '창고코드',
    STOCKTAKING_TYPE VARCHAR(20)    NOT NULL    COMMENT '실사유형',
    STATUS          VARCHAR(20)     NOT NULL    DEFAULT '진행' COMMENT '상태',
    START_DTM       DATETIME        NULL        COMMENT '시작일시',
    END_DTM         DATETIME        NULL        COMMENT '종료일시',
    MANAGER_ID      VARCHAR(20)     NULL        COMMENT '담당자ID',
    APPROVE_USER_ID VARCHAR(20)     NULL        COMMENT '승인자ID',
    APPROVE_DTM     DATETIME        NULL        COMMENT '승인일시',
    STOCKTAKING_RMK VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (STOCKTAKING_ID),
    UNIQUE KEY UK_INV_STOCKTAKING (STOCKTAKING_NO),
    CONSTRAINT FK_INV_ST_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_INV_ST_WH FOREIGN KEY (WAREHOUSE_CD) REFERENCES MST_WAREHOUSE(WAREHOUSE_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='재고실사';

-- 7.6 재고실사상세 (INV_STOCKTAKING_DETAIL)
CREATE TABLE INV_STOCKTAKING_DETAIL (
    ST_DETAIL_ID    BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '실사상세ID',
    STOCKTAKING_ID  BIGINT          NOT NULL    COMMENT '실사ID',
    ITEM_CD         VARCHAR(50)     NOT NULL    COMMENT '품목코드',
    LOT_NO          VARCHAR(50)     NULL        COMMENT 'LOT번호',
    LOCATION_CD     VARCHAR(50)     NULL        COMMENT '로케이션',
    BOOK_QTY        DECIMAL(15,3)   NOT NULL    COMMENT '장부수량',
    ACTUAL_QTY      DECIMAL(15,3)   NULL        COMMENT '실사수량',
    DIFF_QTY        DECIMAL(15,3)   GENERATED ALWAYS AS (COALESCE(ACTUAL_QTY, 0) - BOOK_QTY) STORED COMMENT '차이수량',
    DIFF_REASON     VARCHAR(200)    NULL        COMMENT '차이사유',
    ADJUST_YN       CHAR(1)         NOT NULL    DEFAULT 'N' COMMENT '조정여부',
    ADJUST_DTM      DATETIME        NULL        COMMENT '조정일시',
    ST_DTL_RMK      VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (ST_DETAIL_ID),
    CONSTRAINT FK_INV_ST_DTL_ST FOREIGN KEY (STOCKTAKING_ID) REFERENCES INV_STOCKTAKING(STOCKTAKING_ID),
    CONSTRAINT FK_INV_ST_DTL_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='재고실사상세';

-- 7.7 입고예정 (INV_RECEIVE_PLAN)
CREATE TABLE INV_RECEIVE_PLAN (
    RECEIVE_PLAN_ID BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '입고예정ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    RECEIVE_PLAN_NO VARCHAR(30)     NOT NULL    COMMENT '입고예정번호',
    PLAN_DT         DATE            NOT NULL    COMMENT '예정일자',
    RECEIVE_TYPE    VARCHAR(20)     NOT NULL    COMMENT '입고유형',
    VENDOR_CD       VARCHAR(50)     NULL        COMMENT '거래처코드',
    PO_NO           VARCHAR(50)     NULL        COMMENT '발주번호',
    ITEM_CD         VARCHAR(50)     NOT NULL    COMMENT '품목코드',
    PLAN_QTY        DECIMAL(15,3)   NOT NULL    COMMENT '예정수량',
    RECEIVE_QTY     DECIMAL(15,3)   NULL        DEFAULT 0 COMMENT '입고수량',
    WAREHOUSE_CD    VARCHAR(20)     NULL        COMMENT '입고창고',
    STATUS          VARCHAR(20)     NOT NULL    DEFAULT '예정' COMMENT '상태',
    PLAN_RMK        VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (RECEIVE_PLAN_ID),
    UNIQUE KEY UK_INV_RECEIVE_PLAN (RECEIVE_PLAN_NO),
    CONSTRAINT FK_INV_RCV_PLAN_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_INV_RCV_PLAN_VENDOR FOREIGN KEY (VENDOR_CD) REFERENCES MST_VENDOR(VENDOR_CD),
    CONSTRAINT FK_INV_RCV_PLAN_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD),
    CONSTRAINT FK_INV_RCV_PLAN_WH FOREIGN KEY (WAREHOUSE_CD) REFERENCES MST_WAREHOUSE(WAREHOUSE_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='입고예정';

-- 7.8 출고예정 (INV_ISSUE_PLAN)
CREATE TABLE INV_ISSUE_PLAN (
    ISSUE_PLAN_ID   BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '출고예정ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    ISSUE_PLAN_NO   VARCHAR(30)     NOT NULL    COMMENT '출고예정번호',
    PLAN_DT         DATE            NOT NULL    COMMENT '예정일자',
    ISSUE_TYPE      VARCHAR(20)     NOT NULL    COMMENT '출고유형',
    CUSTOMER_CD     VARCHAR(50)     NULL        COMMENT '고객코드',
    ORDER_NO        VARCHAR(50)     NULL        COMMENT '주문번호',
    WO_ID           BIGINT          NULL        COMMENT '작업지시ID',
    ITEM_CD         VARCHAR(50)     NOT NULL    COMMENT '품목코드',
    PLAN_QTY        DECIMAL(15,3)   NOT NULL    COMMENT '예정수량',
    ISSUE_QTY       DECIMAL(15,3)   NULL        DEFAULT 0 COMMENT '출고수량',
    WAREHOUSE_CD    VARCHAR(20)     NULL        COMMENT '출고창고',
    STATUS          VARCHAR(20)     NOT NULL    DEFAULT '예정' COMMENT '상태',
    PLAN_RMK        VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (ISSUE_PLAN_ID),
    UNIQUE KEY UK_INV_ISSUE_PLAN (ISSUE_PLAN_NO),
    CONSTRAINT FK_INV_ISSUE_PLAN_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_INV_ISSUE_PLAN_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD),
    CONSTRAINT FK_INV_ISSUE_PLAN_WO FOREIGN KEY (WO_ID) REFERENCES PLN_WORK_ORDER(WO_ID),
    CONSTRAINT FK_INV_ISSUE_PLAN_WH FOREIGN KEY (WAREHOUSE_CD) REFERENCES MST_WAREHOUSE(WAREHOUSE_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='출고예정';

-- ------------------------------------------------------------
-- 재고관리 인덱스 생성
-- ------------------------------------------------------------
CREATE INDEX IDX_INV_STOCK_01 ON INV_STOCK(PLANT_CD, WAREHOUSE_CD, ITEM_CD);
CREATE INDEX IDX_INV_STOCK_02 ON INV_STOCK(ITEM_CD, LOT_NO);
CREATE INDEX IDX_INV_STOCK_03 ON INV_STOCK(STOCK_STATUS);
CREATE INDEX IDX_INV_STOCK_04 ON INV_STOCK(EXPIRE_DT);

CREATE INDEX IDX_INV_TRANS_HIS_01 ON INV_TRANS_HIS(PLANT_CD, TRANS_DT);
CREATE INDEX IDX_INV_TRANS_HIS_02 ON INV_TRANS_HIS(ITEM_CD, LOT_NO);
CREATE INDEX IDX_INV_TRANS_HIS_03 ON INV_TRANS_HIS(TRANS_TYPE, TRANS_REASON);
CREATE INDEX IDX_INV_TRANS_HIS_04 ON INV_TRANS_HIS(REF_TYPE, REF_NO);
CREATE INDEX IDX_INV_TRANS_HIS_05 ON INV_TRANS_HIS(VENDOR_CD);

CREATE INDEX IDX_INV_LOT_01 ON INV_LOT(PLANT_CD, ITEM_CD);
CREATE INDEX IDX_INV_LOT_02 ON INV_LOT(EXPIRE_DT);
CREATE INDEX IDX_INV_LOT_03 ON INV_LOT(LOT_STATUS);
CREATE INDEX IDX_INV_LOT_04 ON INV_LOT(VENDOR_CD);
CREATE INDEX IDX_INV_LOT_05 ON INV_LOT(WO_ID);

CREATE INDEX IDX_INV_LOT_TRACE_01 ON INV_LOT_TRACE(LOT_NO);
CREATE INDEX IDX_INV_LOT_TRACE_02 ON INV_LOT_TRACE(PARENT_LOT_NO);
CREATE INDEX IDX_INV_LOT_TRACE_03 ON INV_LOT_TRACE(CHILD_LOT_NO);
CREATE INDEX IDX_INV_LOT_TRACE_04 ON INV_LOT_TRACE(ITEM_CD);

CREATE INDEX IDX_INV_STOCKTAKING_01 ON INV_STOCKTAKING(PLANT_CD, STOCKTAKING_DT);
CREATE INDEX IDX_INV_STOCKTAKING_02 ON INV_STOCKTAKING(WAREHOUSE_CD);

CREATE INDEX IDX_INV_ST_DTL_01 ON INV_STOCKTAKING_DETAIL(STOCKTAKING_ID);
CREATE INDEX IDX_INV_ST_DTL_02 ON INV_STOCKTAKING_DETAIL(ITEM_CD);

CREATE INDEX IDX_INV_RCV_PLAN_01 ON INV_RECEIVE_PLAN(PLANT_CD, PLAN_DT);
CREATE INDEX IDX_INV_RCV_PLAN_02 ON INV_RECEIVE_PLAN(VENDOR_CD);
CREATE INDEX IDX_INV_RCV_PLAN_03 ON INV_RECEIVE_PLAN(ITEM_CD);

CREATE INDEX IDX_INV_ISSUE_PLAN_01 ON INV_ISSUE_PLAN(PLANT_CD, PLAN_DT);
CREATE INDEX IDX_INV_ISSUE_PLAN_02 ON INV_ISSUE_PLAN(WO_ID);
CREATE INDEX IDX_INV_ISSUE_PLAN_03 ON INV_ISSUE_PLAN(ITEM_CD);
