-- ============================================================
-- MES 시스템 데이터베이스 DDL 스크립트
-- DBMS: MariaDB 10.x
-- 파일: mes_ddl_05_equipment.sql (설비관리)
-- 작성일: 2025-01-19
-- ============================================================

USE MES_DB;

-- ------------------------------------------------------------
-- 8. 설비관리 테이블
-- ------------------------------------------------------------

-- 8.1 설비가동현황 (EQP_OPER_STATUS)
CREATE TABLE EQP_OPER_STATUS (
    OPER_ID         BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '가동ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    EQUIPMENT_CD    VARCHAR(20)     NOT NULL    COMMENT '설비코드',
    OPER_DT         DATE            NOT NULL    COMMENT '가동일자',
    SHIFT           VARCHAR(10)     NOT NULL    COMMENT '근무조',
    OPER_STATUS     VARCHAR(20)     NOT NULL    COMMENT '가동상태',
    START_DTM       DATETIME        NOT NULL    COMMENT '시작일시',
    END_DTM         DATETIME        NULL        COMMENT '종료일시',
    OPER_TIME       DECIMAL(10,2)   NULL        COMMENT '가동시간(분)',
    WO_ID           BIGINT          NULL        COMMENT '작업지시ID',
    ITEM_CD         VARCHAR(50)     NULL        COMMENT '품목코드',
    PROD_QTY        DECIMAL(15,3)   NULL        COMMENT '생산수량',
    WORKER_ID       VARCHAR(20)     NULL        COMMENT '작업자ID',
    OPER_RMK        VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (OPER_ID),
    CONSTRAINT FK_EQP_OPER_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_EQP_OPER_EQP FOREIGN KEY (EQUIPMENT_CD) REFERENCES MST_EQUIPMENT(EQUIPMENT_CD),
    CONSTRAINT FK_EQP_OPER_WO FOREIGN KEY (WO_ID) REFERENCES PLN_WORK_ORDER(WO_ID),
    CONSTRAINT FK_EQP_OPER_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD),
    CONSTRAINT FK_EQP_OPER_WORKER FOREIGN KEY (WORKER_ID) REFERENCES MST_WORKER(WORKER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='설비가동현황';

-- 8.2 비가동코드 (EQP_DOWNTIME_CODE)
CREATE TABLE EQP_DOWNTIME_CODE (
    DOWNTIME_CD     VARCHAR(20)     NOT NULL    COMMENT '비가동코드',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    DOWNTIME_NM     VARCHAR(100)    NOT NULL    COMMENT '비가동명',
    DOWNTIME_TYPE   VARCHAR(20)     NOT NULL    COMMENT '비가동유형',
    DOWNTIME_GRP    VARCHAR(50)     NULL        COMMENT '비가동그룹',
    PLANNED_YN      CHAR(1)         NOT NULL    DEFAULT 'N' COMMENT '계획여부',
    SORT_SEQ        INT             NOT NULL    DEFAULT 0 COMMENT '정렬순서',
    USE_YN          CHAR(1)         NOT NULL    DEFAULT 'Y' COMMENT '사용여부',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (DOWNTIME_CD),
    CONSTRAINT FK_EQP_DT_CODE_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='비가동코드';

-- 8.3 비가동이력 (EQP_DOWNTIME)
CREATE TABLE EQP_DOWNTIME (
    DOWNTIME_ID     BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '비가동ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    EQUIPMENT_CD    VARCHAR(20)     NOT NULL    COMMENT '설비코드',
    DOWNTIME_DT     DATE            NOT NULL    COMMENT '비가동일자',
    DOWNTIME_TYPE   VARCHAR(20)     NOT NULL    COMMENT '비가동유형',
    DOWNTIME_CD     VARCHAR(20)     NOT NULL    COMMENT '비가동코드',
    DOWNTIME_REASON VARCHAR(500)    NULL        COMMENT '비가동사유',
    START_DTM       DATETIME        NOT NULL    COMMENT '시작일시',
    END_DTM         DATETIME        NULL        COMMENT '종료일시',
    DOWNTIME_MIN    DECIMAL(10,2)   NULL        COMMENT '비가동시간(분)',
    WO_ID           BIGINT          NULL        COMMENT '작업지시ID',
    OPER_ID         BIGINT          NULL        COMMENT '가동ID',
    ACTION_CONTENT  VARCHAR(500)    NULL        COMMENT '조치내용',
    ACTION_USER_ID  VARCHAR(20)     NULL        COMMENT '조치자ID',
    ACTION_DTM      DATETIME        NULL        COMMENT '조치일시',
    REPORTER_ID     VARCHAR(20)     NULL        COMMENT '보고자ID',
    DOWNTIME_RMK    VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (DOWNTIME_ID),
    CONSTRAINT FK_EQP_DOWNTIME_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_EQP_DOWNTIME_EQP FOREIGN KEY (EQUIPMENT_CD) REFERENCES MST_EQUIPMENT(EQUIPMENT_CD),
    CONSTRAINT FK_EQP_DOWNTIME_CD FOREIGN KEY (DOWNTIME_CD) REFERENCES EQP_DOWNTIME_CODE(DOWNTIME_CD),
    CONSTRAINT FK_EQP_DOWNTIME_WO FOREIGN KEY (WO_ID) REFERENCES PLN_WORK_ORDER(WO_ID),
    CONSTRAINT FK_EQP_DOWNTIME_OPER FOREIGN KEY (OPER_ID) REFERENCES EQP_OPER_STATUS(OPER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='비가동이력';

-- 8.4 정비계획 (EQP_MAINT_PLAN)
CREATE TABLE EQP_MAINT_PLAN (
    MAINT_PLAN_ID   BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '정비계획ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    EQUIPMENT_CD    VARCHAR(20)     NOT NULL    COMMENT '설비코드',
    MAINT_PLAN_NM   VARCHAR(100)    NOT NULL    COMMENT '정비계획명',
    MAINT_TYPE      VARCHAR(20)     NOT NULL    COMMENT '정비유형',
    CYCLE_TYPE      VARCHAR(20)     NOT NULL    COMMENT '주기유형',
    CYCLE_VALUE     INT             NOT NULL    COMMENT '주기값',
    CYCLE_UNIT      VARCHAR(20)     NOT NULL    DEFAULT '일' COMMENT '주기단위',
    BASE_DT         DATE            NULL        COMMENT '기준일',
    LAST_MAINT_DT   DATE            NULL        COMMENT '최종정비일',
    NEXT_MAINT_DT   DATE            NULL        COMMENT '다음정비예정일',
    LEAD_TIME       INT             NULL        DEFAULT 0 COMMENT '사전알림(일)',
    EST_MAINT_TIME  DECIMAL(10,2)   NULL        COMMENT '예상정비시간(분)',
    EST_COST        DECIMAL(18,2)   NULL        COMMENT '예상비용',
    MAINT_CHECKLIST TEXT            NULL        COMMENT '정비체크리스트',
    MAINT_CONTENT   VARCHAR(1000)   NULL        COMMENT '정비내용',
    MANAGER_ID      VARCHAR(20)     NULL        COMMENT '담당자ID',
    USE_YN          CHAR(1)         NOT NULL    DEFAULT 'Y' COMMENT '사용여부',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (MAINT_PLAN_ID),
    CONSTRAINT FK_EQP_MAINT_PLAN_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_EQP_MAINT_PLAN_EQP FOREIGN KEY (EQUIPMENT_CD) REFERENCES MST_EQUIPMENT(EQUIPMENT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='정비계획';

-- 8.5 정비이력 (EQP_MAINT_HIS)
CREATE TABLE EQP_MAINT_HIS (
    MAINT_ID        BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '정비ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    EQUIPMENT_CD    VARCHAR(20)     NOT NULL    COMMENT '설비코드',
    MAINT_NO        VARCHAR(30)     NOT NULL    COMMENT '정비번호',
    MAINT_TYPE      VARCHAR(20)     NOT NULL    COMMENT '정비유형',
    MAINT_DT        DATE            NOT NULL    COMMENT '정비일자',
    MAINT_PLAN_ID   BIGINT          NULL        COMMENT '정비계획ID',
    DOWNTIME_ID     BIGINT          NULL        COMMENT '비가동ID',
    START_DTM       DATETIME        NOT NULL    COMMENT '시작일시',
    END_DTM         DATETIME        NULL        COMMENT '종료일시',
    MAINT_TIME      DECIMAL(10,2)   NULL        COMMENT '정비시간(분)',
    MAINT_WORKER_ID VARCHAR(20)     NULL        COMMENT '정비자ID',
    MAINT_TEAM      VARCHAR(100)    NULL        COMMENT '정비팀',
    MAINT_CONTENT   VARCHAR(1000)   NULL        COMMENT '정비내용',
    SYMPTOM         VARCHAR(500)    NULL        COMMENT '고장증상',
    CAUSE           VARCHAR(500)    NULL        COMMENT '고장원인',
    ACTION          VARCHAR(500)    NULL        COMMENT '조치내용',
    PART_REPLACED   VARCHAR(500)    NULL        COMMENT '교체부품',
    PART_COST       DECIMAL(18,2)   NULL        DEFAULT 0 COMMENT '부품비용',
    LABOR_COST      DECIMAL(18,2)   NULL        DEFAULT 0 COMMENT '인건비',
    OTHER_COST      DECIMAL(18,2)   NULL        DEFAULT 0 COMMENT '기타비용',
    MAINT_COST      DECIMAL(18,2)   GENERATED ALWAYS AS (COALESCE(PART_COST,0) + COALESCE(LABOR_COST,0) + COALESCE(OTHER_COST,0)) STORED COMMENT '총정비비용',
    MAINT_RESULT    VARCHAR(20)     NOT NULL    DEFAULT '진행' COMMENT '정비결과',
    NEXT_MAINT_DT   DATE            NULL        COMMENT '다음정비예정일',
    MAINT_RMK       VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (MAINT_ID),
    UNIQUE KEY UK_EQP_MAINT_HIS (MAINT_NO),
    CONSTRAINT FK_EQP_MAINT_HIS_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_EQP_MAINT_HIS_EQP FOREIGN KEY (EQUIPMENT_CD) REFERENCES MST_EQUIPMENT(EQUIPMENT_CD),
    CONSTRAINT FK_EQP_MAINT_HIS_PLAN FOREIGN KEY (MAINT_PLAN_ID) REFERENCES EQP_MAINT_PLAN(MAINT_PLAN_ID),
    CONSTRAINT FK_EQP_MAINT_HIS_DT FOREIGN KEY (DOWNTIME_ID) REFERENCES EQP_DOWNTIME(DOWNTIME_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='정비이력';

-- 8.6 정비점검체크리스트 (EQP_MAINT_CHECK)
CREATE TABLE EQP_MAINT_CHECK (
    CHECK_ID        BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '체크ID',
    MAINT_ID        BIGINT          NOT NULL    COMMENT '정비ID',
    CHECK_SEQ       INT             NOT NULL    COMMENT '점검순서',
    CHECK_ITEM      VARCHAR(200)    NOT NULL    COMMENT '점검항목',
    CHECK_METHOD    VARCHAR(500)    NULL        COMMENT '점검방법',
    CHECK_STANDARD  VARCHAR(200)    NULL        COMMENT '점검기준',
    CHECK_RESULT    VARCHAR(20)     NULL        COMMENT '점검결과',
    MEASURE_VALUE   VARCHAR(100)    NULL        COMMENT '측정값',
    CHECK_RMK       VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    PRIMARY KEY (CHECK_ID),
    CONSTRAINT FK_EQP_MAINT_CHECK_MAINT FOREIGN KEY (MAINT_ID) REFERENCES EQP_MAINT_HIS(MAINT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='정비점검체크리스트';

-- 8.7 설비부품 (EQP_SPARE_PART)
CREATE TABLE EQP_SPARE_PART (
    SPARE_PART_ID   BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '부품ID',
    EQUIPMENT_CD    VARCHAR(20)     NOT NULL    COMMENT '설비코드',
    PART_CD         VARCHAR(50)     NOT NULL    COMMENT '부품코드',
    PART_NM         VARCHAR(100)    NOT NULL    COMMENT '부품명',
    PART_SPEC       VARCHAR(200)    NULL        COMMENT '부품규격',
    MAKER           VARCHAR(100)    NULL        COMMENT '제조사',
    STOCK_QTY       DECIMAL(15,3)   NULL        DEFAULT 0 COMMENT '재고수량',
    SAFETY_QTY      DECIMAL(15,3)   NULL        COMMENT '안전재고',
    UNIT            VARCHAR(20)     NULL        COMMENT '단위',
    UNIT_PRICE      DECIMAL(18,2)   NULL        COMMENT '단가',
    REPLACE_CYCLE   INT             NULL        COMMENT '교체주기(일)',
    LAST_REPLACE_DT DATE            NULL        COMMENT '최종교체일',
    LOCATION        VARCHAR(100)    NULL        COMMENT '보관위치',
    USE_YN          CHAR(1)         NOT NULL    DEFAULT 'Y' COMMENT '사용여부',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (SPARE_PART_ID),
    UNIQUE KEY UK_EQP_SPARE_PART (EQUIPMENT_CD, PART_CD),
    CONSTRAINT FK_EQP_SPARE_PART_EQP FOREIGN KEY (EQUIPMENT_CD) REFERENCES MST_EQUIPMENT(EQUIPMENT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='설비부품';

-- 8.8 설비파라미터 (EQP_PARAMETER)
CREATE TABLE EQP_PARAMETER (
    PARAM_ID        BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '파라미터ID',
    EQUIPMENT_CD    VARCHAR(20)     NOT NULL    COMMENT '설비코드',
    PARAM_CD        VARCHAR(50)     NOT NULL    COMMENT '파라미터코드',
    PARAM_NM        VARCHAR(100)    NOT NULL    COMMENT '파라미터명',
    PARAM_TYPE      VARCHAR(20)     NULL        COMMENT '파라미터유형',
    DATA_TYPE       VARCHAR(20)     NOT NULL    DEFAULT 'NUMBER' COMMENT '데이터유형',
    UNIT            VARCHAR(20)     NULL        COMMENT '단위',
    LSL             DECIMAL(15,5)   NULL        COMMENT '하한값',
    USL             DECIMAL(15,5)   NULL        COMMENT '상한값',
    TARGET_VALUE    DECIMAL(15,5)   NULL        COMMENT '목표값',
    CURRENT_VALUE   DECIMAL(15,5)   NULL        COMMENT '현재값',
    LAST_UPDATE_DTM DATETIME        NULL        COMMENT '최종갱신일시',
    USE_YN          CHAR(1)         NOT NULL    DEFAULT 'Y' COMMENT '사용여부',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (PARAM_ID),
    UNIQUE KEY UK_EQP_PARAMETER (EQUIPMENT_CD, PARAM_CD),
    CONSTRAINT FK_EQP_PARAM_EQP FOREIGN KEY (EQUIPMENT_CD) REFERENCES MST_EQUIPMENT(EQUIPMENT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='설비파라미터';

-- 8.9 설비파라미터이력 (EQP_PARAMETER_HIS)
CREATE TABLE EQP_PARAMETER_HIS (
    PARAM_HIS_ID    BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '파라미터이력ID',
    PARAM_ID        BIGINT          NOT NULL    COMMENT '파라미터ID',
    EQUIPMENT_CD    VARCHAR(20)     NOT NULL    COMMENT '설비코드',
    MEASURE_DTM     DATETIME        NOT NULL    COMMENT '측정일시',
    MEASURE_VALUE   DECIMAL(15,5)   NOT NULL    COMMENT '측정값',
    WO_ID           BIGINT          NULL        COMMENT '작업지시ID',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    PRIMARY KEY (PARAM_HIS_ID),
    CONSTRAINT FK_EQP_PARAM_HIS_PARAM FOREIGN KEY (PARAM_ID) REFERENCES EQP_PARAMETER(PARAM_ID),
    CONSTRAINT FK_EQP_PARAM_HIS_EQP FOREIGN KEY (EQUIPMENT_CD) REFERENCES MST_EQUIPMENT(EQUIPMENT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='설비파라미터이력';

-- ------------------------------------------------------------
-- 설비관리 인덱스 생성
-- ------------------------------------------------------------
CREATE INDEX IDX_EQP_OPER_STATUS_01 ON EQP_OPER_STATUS(EQUIPMENT_CD, OPER_DT);
CREATE INDEX IDX_EQP_OPER_STATUS_02 ON EQP_OPER_STATUS(PLANT_CD, OPER_DT);
CREATE INDEX IDX_EQP_OPER_STATUS_03 ON EQP_OPER_STATUS(WO_ID);
CREATE INDEX IDX_EQP_OPER_STATUS_04 ON EQP_OPER_STATUS(OPER_STATUS);

CREATE INDEX IDX_EQP_DOWNTIME_01 ON EQP_DOWNTIME(EQUIPMENT_CD, DOWNTIME_DT);
CREATE INDEX IDX_EQP_DOWNTIME_02 ON EQP_DOWNTIME(PLANT_CD, DOWNTIME_DT);
CREATE INDEX IDX_EQP_DOWNTIME_03 ON EQP_DOWNTIME(DOWNTIME_CD);
CREATE INDEX IDX_EQP_DOWNTIME_04 ON EQP_DOWNTIME(DOWNTIME_TYPE);

CREATE INDEX IDX_EQP_MAINT_PLAN_01 ON EQP_MAINT_PLAN(EQUIPMENT_CD);
CREATE INDEX IDX_EQP_MAINT_PLAN_02 ON EQP_MAINT_PLAN(NEXT_MAINT_DT);

CREATE INDEX IDX_EQP_MAINT_HIS_01 ON EQP_MAINT_HIS(EQUIPMENT_CD, MAINT_DT);
CREATE INDEX IDX_EQP_MAINT_HIS_02 ON EQP_MAINT_HIS(PLANT_CD, MAINT_DT);
CREATE INDEX IDX_EQP_MAINT_HIS_03 ON EQP_MAINT_HIS(MAINT_TYPE);
CREATE INDEX IDX_EQP_MAINT_HIS_04 ON EQP_MAINT_HIS(MAINT_PLAN_ID);

CREATE INDEX IDX_EQP_MAINT_CHECK_01 ON EQP_MAINT_CHECK(MAINT_ID);

CREATE INDEX IDX_EQP_SPARE_PART_01 ON EQP_SPARE_PART(EQUIPMENT_CD);

CREATE INDEX IDX_EQP_PARAMETER_01 ON EQP_PARAMETER(EQUIPMENT_CD);

CREATE INDEX IDX_EQP_PARAM_HIS_01 ON EQP_PARAMETER_HIS(PARAM_ID, MEASURE_DTM);
CREATE INDEX IDX_EQP_PARAM_HIS_02 ON EQP_PARAMETER_HIS(EQUIPMENT_CD, MEASURE_DTM);
