-- ============================================================
-- MES 시스템 데이터베이스 DDL 스크립트
-- DBMS: MariaDB 10.x
-- 파일: mes_ddl_02_production.sql (생산계획, 생산실적)
-- 작성일: 2025-01-19
-- ============================================================

USE MES_DB;

-- ------------------------------------------------------------
-- 4. 생산계획 테이블
-- ------------------------------------------------------------

-- 4.1 생산계획 (PLN_PROD_PLAN)
CREATE TABLE PLN_PROD_PLAN (
    PLAN_ID         BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '계획ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    PLAN_NO         VARCHAR(30)     NOT NULL    COMMENT '계획번호',
    PLAN_DT         DATE            NOT NULL    COMMENT '계획일자',
    PLAN_TYPE       VARCHAR(20)     NOT NULL    COMMENT '계획유형',
    ITEM_CD         VARCHAR(50)     NOT NULL    COMMENT '품목코드',
    PLAN_QTY        DECIMAL(15,3)   NOT NULL    COMMENT '계획수량',
    PLAN_START_DT   DATE            NOT NULL    COMMENT '계획시작일',
    PLAN_END_DT     DATE            NOT NULL    COMMENT '계획종료일',
    PRIORITY        INT             NULL        DEFAULT 5 COMMENT '우선순위',
    ORDER_NO        VARCHAR(50)     NULL        COMMENT '수주번호',
    CUSTOMER_CD     VARCHAR(50)     NULL        COMMENT '고객코드',
    CUSTOMER_NM     VARCHAR(100)    NULL        COMMENT '고객명',
    DELIVERY_DT     DATE            NULL        COMMENT '납기일',
    PLAN_STATUS     VARCHAR(20)     NOT NULL    DEFAULT '계획' COMMENT '계획상태',
    RESULT_QTY      DECIMAL(15,3)   NULL        DEFAULT 0 COMMENT '실적수량',
    PLAN_RMK        VARCHAR(500)    NULL        COMMENT '비고',
    APPROVE_USER_ID VARCHAR(50)     NULL        COMMENT '승인자ID',
    APPROVE_DTM     DATETIME        NULL        COMMENT '승인일시',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (PLAN_ID),
    UNIQUE KEY UK_PLN_PROD_PLAN (PLAN_NO),
    CONSTRAINT FK_PLN_PROD_PLAN_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_PLN_PROD_PLAN_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='생산계획';

-- 4.2 작업지시 (PLN_WORK_ORDER)
CREATE TABLE PLN_WORK_ORDER (
    WO_ID           BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '작업지시ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    WO_NO           VARCHAR(30)     NOT NULL    COMMENT '작업지시번호',
    PLAN_ID         BIGINT          NULL        COMMENT '계획ID',
    WO_DT           DATE            NOT NULL    COMMENT '작업지시일',
    ITEM_CD         VARCHAR(50)     NOT NULL    COMMENT '품목코드',
    WO_QTY          DECIMAL(15,3)   NOT NULL    COMMENT '지시수량',
    WORKCENTER_CD   VARCHAR(20)     NULL        COMMENT '작업장코드',
    EQUIPMENT_CD    VARCHAR(20)     NULL        COMMENT '설비코드',
    WORKER_ID       VARCHAR(20)     NULL        COMMENT '작업자ID',
    PLAN_START_DTM  DATETIME        NOT NULL    COMMENT '계획시작일시',
    PLAN_END_DTM    DATETIME        NOT NULL    COMMENT '계획종료일시',
    ACTUAL_START_DTM DATETIME       NULL        COMMENT '실제시작일시',
    ACTUAL_END_DTM  DATETIME        NULL        COMMENT '실제종료일시',
    GOOD_QTY        DECIMAL(15,3)   NULL        DEFAULT 0 COMMENT '양품수량',
    DEFECT_QTY      DECIMAL(15,3)   NULL        DEFAULT 0 COMMENT '불량수량',
    WO_STATUS       VARCHAR(20)     NOT NULL    DEFAULT '대기' COMMENT '작업상태',
    PRIORITY        INT             NULL        DEFAULT 5 COMMENT '우선순위',
    LOT_NO          VARCHAR(50)     NULL        COMMENT 'LOT번호',
    PARENT_WO_ID    BIGINT          NULL        COMMENT '상위작업지시ID',
    ORDER_NO        VARCHAR(50)     NULL        COMMENT '수주번호',
    DELIVERY_DT     DATE            NULL        COMMENT '납기일',
    WO_RMK          VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (WO_ID),
    UNIQUE KEY UK_PLN_WORK_ORDER (WO_NO),
    CONSTRAINT FK_PLN_WO_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_PLN_WO_PLAN FOREIGN KEY (PLAN_ID) REFERENCES PLN_PROD_PLAN(PLAN_ID),
    CONSTRAINT FK_PLN_WO_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD),
    CONSTRAINT FK_PLN_WO_WC FOREIGN KEY (WORKCENTER_CD) REFERENCES MST_WORKCENTER(WORKCENTER_CD),
    CONSTRAINT FK_PLN_WO_EQP FOREIGN KEY (EQUIPMENT_CD) REFERENCES MST_EQUIPMENT(EQUIPMENT_CD),
    CONSTRAINT FK_PLN_WO_WORKER FOREIGN KEY (WORKER_ID) REFERENCES MST_WORKER(WORKER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='작업지시';

-- 4.3 작업지시 자재 (PLN_WO_MATERIAL)
CREATE TABLE PLN_WO_MATERIAL (
    WO_MTL_ID       BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '자재ID',
    WO_ID           BIGINT          NOT NULL    COMMENT '작업지시ID',
    ITEM_CD         VARCHAR(50)     NOT NULL    COMMENT '품목코드',
    PLAN_QTY        DECIMAL(15,5)   NOT NULL    COMMENT '계획수량',
    ISSUE_QTY       DECIMAL(15,5)   NULL        DEFAULT 0 COMMENT '출고수량',
    RETURN_QTY      DECIMAL(15,5)   NULL        DEFAULT 0 COMMENT '반납수량',
    LOSS_RATE       DECIMAL(5,2)    NULL        DEFAULT 0 COMMENT '손실율(%)',
    WAREHOUSE_CD    VARCHAR(20)     NULL        COMMENT '창고코드',
    LOT_NO          VARCHAR(50)     NULL        COMMENT 'LOT번호',
    MTL_RMK         VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (WO_MTL_ID),
    CONSTRAINT FK_PLN_WO_MTL_WO FOREIGN KEY (WO_ID) REFERENCES PLN_WORK_ORDER(WO_ID),
    CONSTRAINT FK_PLN_WO_MTL_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='작업지시자재';

-- ------------------------------------------------------------
-- 5. 생산실적 테이블
-- ------------------------------------------------------------

-- 5.1 작업실적 (PRD_WORK_RESULT)
CREATE TABLE PRD_WORK_RESULT (
    RESULT_ID       BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '실적ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    RESULT_NO       VARCHAR(30)     NOT NULL    COMMENT '실적번호',
    WO_ID           BIGINT          NOT NULL    COMMENT '작업지시ID',
    RESULT_DT       DATE            NOT NULL    COMMENT '실적일자',
    SHIFT           VARCHAR(10)     NOT NULL    COMMENT '근무조',
    WORKER_ID       VARCHAR(20)     NOT NULL    COMMENT '작업자ID',
    WORKCENTER_CD   VARCHAR(20)     NOT NULL    COMMENT '작업장코드',
    EQUIPMENT_CD    VARCHAR(20)     NULL        COMMENT '설비코드',
    ITEM_CD         VARCHAR(50)     NOT NULL    COMMENT '품목코드',
    PROD_QTY        DECIMAL(15,3)   NOT NULL    COMMENT '생산수량',
    GOOD_QTY        DECIMAL(15,3)   NOT NULL    COMMENT '양품수량',
    DEFECT_QTY      DECIMAL(15,3)   NULL        DEFAULT 0 COMMENT '불량수량',
    START_DTM       DATETIME        NOT NULL    COMMENT '시작일시',
    END_DTM         DATETIME        NULL        COMMENT '종료일시',
    WORK_TIME       DECIMAL(10,2)   NULL        COMMENT '작업시간(분)',
    SETUP_TIME      DECIMAL(10,2)   NULL        DEFAULT 0 COMMENT '준비시간(분)',
    DOWN_TIME       DECIMAL(10,2)   NULL        DEFAULT 0 COMMENT '비가동시간(분)',
    LOT_NO          VARCHAR(50)     NULL        COMMENT 'LOT번호',
    RESULT_STATUS   VARCHAR(20)     NOT NULL    DEFAULT '진행' COMMENT '실적상태',
    RESULT_RMK      VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (RESULT_ID),
    UNIQUE KEY UK_PRD_WORK_RESULT (RESULT_NO),
    CONSTRAINT FK_PRD_RESULT_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_PRD_RESULT_WO FOREIGN KEY (WO_ID) REFERENCES PLN_WORK_ORDER(WO_ID),
    CONSTRAINT FK_PRD_RESULT_WORKER FOREIGN KEY (WORKER_ID) REFERENCES MST_WORKER(WORKER_ID),
    CONSTRAINT FK_PRD_RESULT_WC FOREIGN KEY (WORKCENTER_CD) REFERENCES MST_WORKCENTER(WORKCENTER_CD),
    CONSTRAINT FK_PRD_RESULT_EQP FOREIGN KEY (EQUIPMENT_CD) REFERENCES MST_EQUIPMENT(EQUIPMENT_CD),
    CONSTRAINT FK_PRD_RESULT_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='작업실적';

-- 5.2 공정실적 (PRD_PROCESS_RESULT)
CREATE TABLE PRD_PROCESS_RESULT (
    PROC_RESULT_ID  BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '공정실적ID',
    RESULT_ID       BIGINT          NOT NULL    COMMENT '작업실적ID',
    ROUTING_ID      BIGINT          NOT NULL    COMMENT '라우팅ID',
    PROCESS_SEQ     INT             NOT NULL    COMMENT '공정순서',
    PROCESS_CD      VARCHAR(20)     NOT NULL    COMMENT '공정코드',
    PROCESS_NM      VARCHAR(100)    NOT NULL    COMMENT '공정명',
    START_DTM       DATETIME        NOT NULL    COMMENT '시작일시',
    END_DTM         DATETIME        NULL        COMMENT '종료일시',
    INPUT_QTY       DECIMAL(15,3)   NOT NULL    COMMENT '투입수량',
    OUTPUT_QTY      DECIMAL(15,3)   NULL        COMMENT '산출수량',
    GOOD_QTY        DECIMAL(15,3)   NULL        COMMENT '양품수량',
    DEFECT_QTY      DECIMAL(15,3)   NULL        DEFAULT 0 COMMENT '불량수량',
    WORKER_ID       VARCHAR(20)     NULL        COMMENT '작업자ID',
    EQUIPMENT_CD    VARCHAR(20)     NULL        COMMENT '설비코드',
    WORK_TIME       DECIMAL(10,2)   NULL        COMMENT '작업시간(분)',
    PROCESS_STATUS  VARCHAR(20)     NOT NULL    DEFAULT '대기' COMMENT '공정상태',
    LOT_NO          VARCHAR(50)     NULL        COMMENT 'LOT번호',
    PROC_RMK        VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (PROC_RESULT_ID),
    CONSTRAINT FK_PRD_PROC_RESULT FOREIGN KEY (RESULT_ID) REFERENCES PRD_WORK_RESULT(RESULT_ID),
    CONSTRAINT FK_PRD_PROC_ROUTING FOREIGN KEY (ROUTING_ID) REFERENCES MST_ROUTING(ROUTING_ID),
    CONSTRAINT FK_PRD_PROC_WORKER FOREIGN KEY (WORKER_ID) REFERENCES MST_WORKER(WORKER_ID),
    CONSTRAINT FK_PRD_PROC_EQP FOREIGN KEY (EQUIPMENT_CD) REFERENCES MST_EQUIPMENT(EQUIPMENT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='공정실적';

-- 5.3 생산불량이력 (PRD_DEFECT_HIS)
CREATE TABLE PRD_DEFECT_HIS (
    DEFECT_ID       BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '불량ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    RESULT_ID       BIGINT          NOT NULL    COMMENT '작업실적ID',
    PROC_RESULT_ID  BIGINT          NULL        COMMENT '공정실적ID',
    DEFECT_DT       DATE            NOT NULL    COMMENT '불량발생일',
    DEFECT_TYPE     VARCHAR(20)     NOT NULL    COMMENT '불량유형',
    DEFECT_CD       VARCHAR(20)     NOT NULL    COMMENT '불량코드',
    DEFECT_NM       VARCHAR(100)    NULL        COMMENT '불량명',
    DEFECT_QTY      DECIMAL(15,3)   NOT NULL    COMMENT '불량수량',
    DEFECT_CAUSE    VARCHAR(500)    NULL        COMMENT '불량원인',
    DEFECT_ACTION   VARCHAR(500)    NULL        COMMENT '조치내용',
    DISPOSITION     VARCHAR(20)     NULL        COMMENT '처리방법',
    DISPOSITION_QTY DECIMAL(15,3)   NULL        COMMENT '처리수량',
    DISPOSITION_DT  DATE            NULL        COMMENT '처리일자',
    ITEM_CD         VARCHAR(50)     NOT NULL    COMMENT '품목코드',
    LOT_NO          VARCHAR(50)     NULL        COMMENT 'LOT번호',
    WORKER_ID       VARCHAR(20)     NULL        COMMENT '작업자ID',
    EQUIPMENT_CD    VARCHAR(20)     NULL        COMMENT '설비코드',
    PROCESS_CD      VARCHAR(20)     NULL        COMMENT '공정코드',
    DEFECT_RMK      VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (DEFECT_ID),
    CONSTRAINT FK_PRD_DEFECT_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_PRD_DEFECT_RESULT FOREIGN KEY (RESULT_ID) REFERENCES PRD_WORK_RESULT(RESULT_ID),
    CONSTRAINT FK_PRD_DEFECT_PROC FOREIGN KEY (PROC_RESULT_ID) REFERENCES PRD_PROCESS_RESULT(PROC_RESULT_ID),
    CONSTRAINT FK_PRD_DEFECT_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='생산불량이력';

-- 5.4 자재투입이력 (PRD_MATERIAL_ISSUE)
CREATE TABLE PRD_MATERIAL_ISSUE (
    ISSUE_ID        BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '투입ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    RESULT_ID       BIGINT          NOT NULL    COMMENT '작업실적ID',
    WO_ID           BIGINT          NOT NULL    COMMENT '작업지시ID',
    ISSUE_DT        DATE            NOT NULL    COMMENT '투입일자',
    ITEM_CD         VARCHAR(50)     NOT NULL    COMMENT '품목코드',
    LOT_NO          VARCHAR(50)     NULL        COMMENT 'LOT번호',
    ISSUE_QTY       DECIMAL(15,5)   NOT NULL    COMMENT '투입수량',
    UNIT            VARCHAR(20)     NOT NULL    COMMENT '단위',
    WAREHOUSE_CD    VARCHAR(20)     NULL        COMMENT '창고코드',
    LOCATION_CD     VARCHAR(50)     NULL        COMMENT '로케이션',
    ISSUE_TYPE      VARCHAR(20)     NOT NULL    DEFAULT '정규투입' COMMENT '투입유형',
    ISSUE_RMK       VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (ISSUE_ID),
    CONSTRAINT FK_PRD_ISSUE_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_PRD_ISSUE_RESULT FOREIGN KEY (RESULT_ID) REFERENCES PRD_WORK_RESULT(RESULT_ID),
    CONSTRAINT FK_PRD_ISSUE_WO FOREIGN KEY (WO_ID) REFERENCES PLN_WORK_ORDER(WO_ID),
    CONSTRAINT FK_PRD_ISSUE_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='자재투입이력';

-- ------------------------------------------------------------
-- 생산계획/실적 인덱스 생성
-- ------------------------------------------------------------
CREATE INDEX IDX_PLN_PROD_PLAN_01 ON PLN_PROD_PLAN(PLANT_CD, PLAN_DT);
CREATE INDEX IDX_PLN_PROD_PLAN_02 ON PLN_PROD_PLAN(ITEM_CD);
CREATE INDEX IDX_PLN_PROD_PLAN_03 ON PLN_PROD_PLAN(PLAN_STATUS);

CREATE INDEX IDX_PLN_WORK_ORDER_01 ON PLN_WORK_ORDER(PLANT_CD, WO_DT, WO_STATUS);
CREATE INDEX IDX_PLN_WORK_ORDER_02 ON PLN_WORK_ORDER(ITEM_CD);
CREATE INDEX IDX_PLN_WORK_ORDER_03 ON PLN_WORK_ORDER(LOT_NO);
CREATE INDEX IDX_PLN_WORK_ORDER_04 ON PLN_WORK_ORDER(WORKCENTER_CD);
CREATE INDEX IDX_PLN_WORK_ORDER_05 ON PLN_WORK_ORDER(PLAN_ID);

CREATE INDEX IDX_PRD_WORK_RESULT_01 ON PRD_WORK_RESULT(WO_ID);
CREATE INDEX IDX_PRD_WORK_RESULT_02 ON PRD_WORK_RESULT(PLANT_CD, RESULT_DT);
CREATE INDEX IDX_PRD_WORK_RESULT_03 ON PRD_WORK_RESULT(ITEM_CD);
CREATE INDEX IDX_PRD_WORK_RESULT_04 ON PRD_WORK_RESULT(LOT_NO);
CREATE INDEX IDX_PRD_WORK_RESULT_05 ON PRD_WORK_RESULT(WORKCENTER_CD);

CREATE INDEX IDX_PRD_PROCESS_RESULT_01 ON PRD_PROCESS_RESULT(RESULT_ID);
CREATE INDEX IDX_PRD_PROCESS_RESULT_02 ON PRD_PROCESS_RESULT(ROUTING_ID);

CREATE INDEX IDX_PRD_DEFECT_HIS_01 ON PRD_DEFECT_HIS(RESULT_ID);
CREATE INDEX IDX_PRD_DEFECT_HIS_02 ON PRD_DEFECT_HIS(PLANT_CD, DEFECT_DT);
CREATE INDEX IDX_PRD_DEFECT_HIS_03 ON PRD_DEFECT_HIS(DEFECT_CD);
CREATE INDEX IDX_PRD_DEFECT_HIS_04 ON PRD_DEFECT_HIS(ITEM_CD, LOT_NO);

CREATE INDEX IDX_PRD_MTL_ISSUE_01 ON PRD_MATERIAL_ISSUE(RESULT_ID);
CREATE INDEX IDX_PRD_MTL_ISSUE_02 ON PRD_MATERIAL_ISSUE(WO_ID);
CREATE INDEX IDX_PRD_MTL_ISSUE_03 ON PRD_MATERIAL_ISSUE(ITEM_CD, LOT_NO);
