-- ============================================================
-- MES 시스템 데이터베이스 DDL 스크립트
-- DBMS: MariaDB 10.x
-- 파일: mes_ddl_03_quality.sql (품질관리)
-- 작성일: 2025-01-19
-- ============================================================

USE MES_DB;

-- ------------------------------------------------------------
-- 6. 품질관리 테이블
-- ------------------------------------------------------------

-- 6.1 불량코드 (QC_DEFECT_CODE)
CREATE TABLE QC_DEFECT_CODE (
    DEFECT_CD       VARCHAR(20)     NOT NULL    COMMENT '불량코드',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    DEFECT_NM       VARCHAR(100)    NOT NULL    COMMENT '불량명',
    DEFECT_TYPE     VARCHAR(20)     NOT NULL    COMMENT '불량유형',
    DEFECT_GRP      VARCHAR(50)     NULL        COMMENT '불량그룹',
    DEFECT_DESC     VARCHAR(500)    NULL        COMMENT '불량설명',
    SEVERITY        VARCHAR(20)     NULL        COMMENT '심각도',
    SORT_SEQ        INT             NOT NULL    DEFAULT 0 COMMENT '정렬순서',
    USE_YN          CHAR(1)         NOT NULL    DEFAULT 'Y' COMMENT '사용여부',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (DEFECT_CD),
    CONSTRAINT FK_QC_DEFECT_CODE_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='불량코드';

-- 6.2 검사기준 (QC_INSPECT_STD)
CREATE TABLE QC_INSPECT_STD (
    INSPECT_STD_ID  BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '검사기준ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    ITEM_CD         VARCHAR(50)     NOT NULL    COMMENT '품목코드',
    INSPECT_TYPE    VARCHAR(20)     NOT NULL    COMMENT '검사유형',
    INSPECT_ITEM_SEQ INT            NOT NULL    COMMENT '검사항목순서',
    INSPECT_ITEM    VARCHAR(100)    NOT NULL    COMMENT '검사항목',
    INSPECT_METHOD  VARCHAR(500)    NULL        COMMENT '검사방법',
    DATA_TYPE       VARCHAR(20)     NOT NULL    DEFAULT 'NUMBER' COMMENT '데이터유형',
    SPEC_VALUE      VARCHAR(100)    NULL        COMMENT '규격값',
    LSL             DECIMAL(15,5)   NULL        COMMENT '하한규격',
    USL             DECIMAL(15,5)   NULL        COMMENT '상한규격',
    TARGET_VALUE    DECIMAL(15,5)   NULL        COMMENT '목표값',
    UNIT            VARCHAR(20)     NULL        COMMENT '단위',
    SAMPLE_SIZE     INT             NULL        DEFAULT 1 COMMENT '샘플크기',
    SAMPLE_METHOD   VARCHAR(50)     NULL        COMMENT '샘플링방법',
    INSPECT_TOOL    VARCHAR(100)    NULL        COMMENT '검사도구',
    MANDATORY_YN    CHAR(1)         NOT NULL    DEFAULT 'Y' COMMENT '필수여부',
    PROCESS_CD      VARCHAR(20)     NULL        COMMENT '공정코드',
    VALID_START_DT  DATE            NULL        COMMENT '유효시작일',
    VALID_END_DT    DATE            NULL        COMMENT '유효종료일',
    STD_RMK         VARCHAR(500)    NULL        COMMENT '비고',
    USE_YN          CHAR(1)         NOT NULL    DEFAULT 'Y' COMMENT '사용여부',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (INSPECT_STD_ID),
    UNIQUE KEY UK_QC_INSPECT_STD (PLANT_CD, ITEM_CD, INSPECT_TYPE, INSPECT_ITEM_SEQ),
    CONSTRAINT FK_QC_INSPECT_STD_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_QC_INSPECT_STD_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='검사기준';

-- 6.3 검사실적 (QC_INSPECT_RESULT)
CREATE TABLE QC_INSPECT_RESULT (
    INSPECT_ID      BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '검사ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    INSPECT_NO      VARCHAR(30)     NOT NULL    COMMENT '검사번호',
    INSPECT_TYPE    VARCHAR(20)     NOT NULL    COMMENT '검사유형',
    INSPECT_DT      DATE            NOT NULL    COMMENT '검사일자',
    ITEM_CD         VARCHAR(50)     NOT NULL    COMMENT '품목코드',
    LOT_NO          VARCHAR(50)     NULL        COMMENT 'LOT번호',
    INSPECT_QTY     DECIMAL(15,3)   NOT NULL    COMMENT '검사수량',
    SAMPLE_QTY      DECIMAL(15,3)   NULL        COMMENT '샘플수량',
    PASS_QTY        DECIMAL(15,3)   NULL        DEFAULT 0 COMMENT '합격수량',
    FAIL_QTY        DECIMAL(15,3)   NULL        DEFAULT 0 COMMENT '불합격수량',
    INSPECTOR_ID    VARCHAR(20)     NOT NULL    COMMENT '검사자ID',
    WO_ID           BIGINT          NULL        COMMENT '작업지시ID',
    RESULT_ID       BIGINT          NULL        COMMENT '작업실적ID',
    RECEIVE_ID      BIGINT          NULL        COMMENT '입고ID',
    VENDOR_CD       VARCHAR(50)     NULL        COMMENT '거래처코드',
    JUDGE_RESULT    VARCHAR(20)     NOT NULL    DEFAULT '대기' COMMENT '판정결과',
    JUDGE_USER_ID   VARCHAR(50)     NULL        COMMENT '판정자ID',
    JUDGE_DTM       DATETIME        NULL        COMMENT '판정일시',
    PROCESS_CD      VARCHAR(20)     NULL        COMMENT '공정코드',
    INSPECT_RMK     VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (INSPECT_ID),
    UNIQUE KEY UK_QC_INSPECT_RESULT (INSPECT_NO),
    CONSTRAINT FK_QC_INSPECT_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_QC_INSPECT_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD),
    CONSTRAINT FK_QC_INSPECT_INSPECTOR FOREIGN KEY (INSPECTOR_ID) REFERENCES MST_WORKER(WORKER_ID),
    CONSTRAINT FK_QC_INSPECT_WO FOREIGN KEY (WO_ID) REFERENCES PLN_WORK_ORDER(WO_ID),
    CONSTRAINT FK_QC_INSPECT_VENDOR FOREIGN KEY (VENDOR_CD) REFERENCES MST_VENDOR(VENDOR_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='검사실적';

-- 6.4 검사상세 (QC_INSPECT_DETAIL)
CREATE TABLE QC_INSPECT_DETAIL (
    INSPECT_DTL_ID  BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '검사상세ID',
    INSPECT_ID      BIGINT          NOT NULL    COMMENT '검사ID',
    INSPECT_STD_ID  BIGINT          NOT NULL    COMMENT '검사기준ID',
    SAMPLE_NO       INT             NOT NULL    DEFAULT 1 COMMENT '샘플번호',
    INSPECT_ITEM    VARCHAR(100)    NOT NULL    COMMENT '검사항목',
    DATA_TYPE       VARCHAR(20)     NOT NULL    COMMENT '데이터유형',
    MEASURE_VALUE   DECIMAL(15,5)   NULL        COMMENT '측정값(숫자)',
    MEASURE_TEXT    VARCHAR(200)    NULL        COMMENT '측정값(텍스트)',
    LSL             DECIMAL(15,5)   NULL        COMMENT '하한규격',
    USL             DECIMAL(15,5)   NULL        COMMENT '상한규격',
    TARGET_VALUE    DECIMAL(15,5)   NULL        COMMENT '목표값',
    JUDGE_RESULT    VARCHAR(20)     NOT NULL    COMMENT '판정결과',
    DEFECT_CD       VARCHAR(20)     NULL        COMMENT '불량코드',
    DETAIL_RMK      VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    PRIMARY KEY (INSPECT_DTL_ID),
    CONSTRAINT FK_QC_INSPECT_DTL_ID FOREIGN KEY (INSPECT_ID) REFERENCES QC_INSPECT_RESULT(INSPECT_ID),
    CONSTRAINT FK_QC_INSPECT_DTL_STD FOREIGN KEY (INSPECT_STD_ID) REFERENCES QC_INSPECT_STD(INSPECT_STD_ID),
    CONSTRAINT FK_QC_INSPECT_DTL_DEFECT FOREIGN KEY (DEFECT_CD) REFERENCES QC_DEFECT_CODE(DEFECT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='검사상세';

-- 6.5 품질불량이력 (QC_DEFECT_HIS)
CREATE TABLE QC_DEFECT_HIS (
    QC_DEFECT_ID    BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '품질불량ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    INSPECT_ID      BIGINT          NOT NULL    COMMENT '검사ID',
    DEFECT_DT       DATE            NOT NULL    COMMENT '불량발생일',
    DEFECT_CD       VARCHAR(20)     NOT NULL    COMMENT '불량코드',
    DEFECT_NM       VARCHAR(100)    NULL        COMMENT '불량명',
    DEFECT_QTY      DECIMAL(15,3)   NOT NULL    COMMENT '불량수량',
    ITEM_CD         VARCHAR(50)     NOT NULL    COMMENT '품목코드',
    LOT_NO          VARCHAR(50)     NULL        COMMENT 'LOT번호',
    DEFECT_CAUSE    VARCHAR(500)    NULL        COMMENT '불량원인',
    CAUSE_CATEGORY  VARCHAR(50)     NULL        COMMENT '원인구분(4M)',
    CORRECTIVE_ACTION VARCHAR(500)  NULL        COMMENT '시정조치',
    PREVENTIVE_ACTION VARCHAR(500)  NULL        COMMENT '예방조치',
    ACTION_USER_ID  VARCHAR(20)     NULL        COMMENT '조치담당자',
    ACTION_DT       DATE            NULL        COMMENT '조치일자',
    DISPOSITION     VARCHAR(20)     NULL        COMMENT '처리방법',
    DISPOSITION_QTY DECIMAL(15,3)   NULL        COMMENT '처리수량',
    DISPOSITION_DT  DATE            NULL        COMMENT '처리일자',
    DEFECT_RMK      VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (QC_DEFECT_ID),
    CONSTRAINT FK_QC_DEFECT_HIS_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_QC_DEFECT_HIS_INSPECT FOREIGN KEY (INSPECT_ID) REFERENCES QC_INSPECT_RESULT(INSPECT_ID),
    CONSTRAINT FK_QC_DEFECT_HIS_CD FOREIGN KEY (DEFECT_CD) REFERENCES QC_DEFECT_CODE(DEFECT_CD),
    CONSTRAINT FK_QC_DEFECT_HIS_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='품질불량이력';

-- 6.6 품질성적서 (QC_COA)
CREATE TABLE QC_COA (
    COA_ID          BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '성적서ID',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    COA_NO          VARCHAR(30)     NOT NULL    COMMENT '성적서번호',
    COA_DT          DATE            NOT NULL    COMMENT '발행일자',
    INSPECT_ID      BIGINT          NOT NULL    COMMENT '검사ID',
    ITEM_CD         VARCHAR(50)     NOT NULL    COMMENT '품목코드',
    LOT_NO          VARCHAR(50)     NULL        COMMENT 'LOT번호',
    SHIP_QTY        DECIMAL(15,3)   NULL        COMMENT '출하수량',
    CUSTOMER_CD     VARCHAR(50)     NULL        COMMENT '고객코드',
    CUSTOMER_NM     VARCHAR(100)    NULL        COMMENT '고객명',
    ORDER_NO        VARCHAR(50)     NULL        COMMENT '주문번호',
    ISSUE_USER_ID   VARCHAR(20)     NOT NULL    COMMENT '발행자ID',
    APPROVE_USER_ID VARCHAR(20)     NULL        COMMENT '승인자ID',
    APPROVE_DTM     DATETIME        NULL        COMMENT '승인일시',
    COA_STATUS      VARCHAR(20)     NOT NULL    DEFAULT '발행' COMMENT '상태',
    COA_RMK         VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (COA_ID),
    UNIQUE KEY UK_QC_COA (COA_NO),
    CONSTRAINT FK_QC_COA_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD),
    CONSTRAINT FK_QC_COA_INSPECT FOREIGN KEY (INSPECT_ID) REFERENCES QC_INSPECT_RESULT(INSPECT_ID),
    CONSTRAINT FK_QC_COA_ITEM FOREIGN KEY (ITEM_CD) REFERENCES MST_ITEM(ITEM_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='품질성적서';

-- 6.7 측정장비 (QC_MEASURE_EQUIP)
CREATE TABLE QC_MEASURE_EQUIP (
    MEASURE_EQUIP_CD VARCHAR(20)    NOT NULL    COMMENT '측정장비코드',
    PLANT_CD        VARCHAR(20)     NOT NULL    COMMENT '공장코드',
    MEASURE_EQUIP_NM VARCHAR(100)   NOT NULL    COMMENT '측정장비명',
    EQUIP_TYPE      VARCHAR(50)     NULL        COMMENT '장비유형',
    MODEL_NM        VARCHAR(100)    NULL        COMMENT '모델명',
    MAKER           VARCHAR(100)    NULL        COMMENT '제조사',
    SERIAL_NO       VARCHAR(100)    NULL        COMMENT '시리얼번호',
    MEASURE_RANGE   VARCHAR(100)    NULL        COMMENT '측정범위',
    RESOLUTION      VARCHAR(50)     NULL        COMMENT '분해능',
    ACCURACY        VARCHAR(50)     NULL        COMMENT '정확도',
    PURCHASE_DT     DATE            NULL        COMMENT '구매일',
    LAST_CAL_DT     DATE            NULL        COMMENT '최종교정일',
    NEXT_CAL_DT     DATE            NULL        COMMENT '다음교정예정일',
    CAL_CYCLE       INT             NULL        COMMENT '교정주기(월)',
    LOCATION        VARCHAR(100)    NULL        COMMENT '보관위치',
    MANAGER_ID      VARCHAR(20)     NULL        COMMENT '담당자ID',
    EQUIP_STATUS    VARCHAR(20)     NOT NULL    DEFAULT '정상' COMMENT '장비상태',
    USE_YN          CHAR(1)         NOT NULL    DEFAULT 'Y' COMMENT '사용여부',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (MEASURE_EQUIP_CD),
    CONSTRAINT FK_QC_MEASURE_EQUIP_PLANT FOREIGN KEY (PLANT_CD) REFERENCES MST_PLANT(PLANT_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='측정장비';

-- 6.8 측정장비 교정이력 (QC_CALIBRATION_HIS)
CREATE TABLE QC_CALIBRATION_HIS (
    CAL_ID          BIGINT          NOT NULL    AUTO_INCREMENT COMMENT '교정ID',
    MEASURE_EQUIP_CD VARCHAR(20)    NOT NULL    COMMENT '측정장비코드',
    CAL_DT          DATE            NOT NULL    COMMENT '교정일자',
    CAL_TYPE        VARCHAR(20)     NOT NULL    COMMENT '교정유형',
    CAL_AGENCY      VARCHAR(100)    NULL        COMMENT '교정기관',
    CAL_RESULT      VARCHAR(20)     NOT NULL    COMMENT '교정결과',
    CAL_CERT_NO     VARCHAR(50)     NULL        COMMENT '교정성적서번호',
    BEFORE_VALUE    VARCHAR(100)    NULL        COMMENT '교정전값',
    AFTER_VALUE     VARCHAR(100)    NULL        COMMENT '교정후값',
    NEXT_CAL_DT     DATE            NULL        COMMENT '다음교정예정일',
    CAL_COST        DECIMAL(18,2)   NULL        COMMENT '교정비용',
    CAL_RMK         VARCHAR(500)    NULL        COMMENT '비고',
    REG_USER_ID     VARCHAR(50)     NOT NULL    COMMENT '등록자ID',
    REG_DTM         DATETIME        NOT NULL    DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    UPD_USER_ID     VARCHAR(50)     NULL        COMMENT '수정자ID',
    UPD_DTM         DATETIME        NULL        ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (CAL_ID),
    CONSTRAINT FK_QC_CAL_HIS_EQUIP FOREIGN KEY (MEASURE_EQUIP_CD) REFERENCES QC_MEASURE_EQUIP(MEASURE_EQUIP_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='측정장비교정이력';

-- ------------------------------------------------------------
-- 품질관리 인덱스 생성
-- ------------------------------------------------------------
CREATE INDEX IDX_QC_DEFECT_CODE_01 ON QC_DEFECT_CODE(PLANT_CD, DEFECT_TYPE);

CREATE INDEX IDX_QC_INSPECT_STD_01 ON QC_INSPECT_STD(ITEM_CD, INSPECT_TYPE);
CREATE INDEX IDX_QC_INSPECT_STD_02 ON QC_INSPECT_STD(PLANT_CD, INSPECT_TYPE);

CREATE INDEX IDX_QC_INSPECT_RESULT_01 ON QC_INSPECT_RESULT(PLANT_CD, INSPECT_DT);
CREATE INDEX IDX_QC_INSPECT_RESULT_02 ON QC_INSPECT_RESULT(ITEM_CD, LOT_NO);
CREATE INDEX IDX_QC_INSPECT_RESULT_03 ON QC_INSPECT_RESULT(INSPECT_TYPE, JUDGE_RESULT);
CREATE INDEX IDX_QC_INSPECT_RESULT_04 ON QC_INSPECT_RESULT(WO_ID);
CREATE INDEX IDX_QC_INSPECT_RESULT_05 ON QC_INSPECT_RESULT(VENDOR_CD);

CREATE INDEX IDX_QC_INSPECT_DETAIL_01 ON QC_INSPECT_DETAIL(INSPECT_ID);
CREATE INDEX IDX_QC_INSPECT_DETAIL_02 ON QC_INSPECT_DETAIL(INSPECT_STD_ID);

CREATE INDEX IDX_QC_DEFECT_HIS_01 ON QC_DEFECT_HIS(PLANT_CD, DEFECT_DT);
CREATE INDEX IDX_QC_DEFECT_HIS_02 ON QC_DEFECT_HIS(INSPECT_ID);
CREATE INDEX IDX_QC_DEFECT_HIS_03 ON QC_DEFECT_HIS(DEFECT_CD);
CREATE INDEX IDX_QC_DEFECT_HIS_04 ON QC_DEFECT_HIS(ITEM_CD, LOT_NO);

CREATE INDEX IDX_QC_COA_01 ON QC_COA(PLANT_CD, COA_DT);
CREATE INDEX IDX_QC_COA_02 ON QC_COA(INSPECT_ID);

CREATE INDEX IDX_QC_MEASURE_EQUIP_01 ON QC_MEASURE_EQUIP(PLANT_CD, EQUIP_STATUS);
CREATE INDEX IDX_QC_MEASURE_EQUIP_02 ON QC_MEASURE_EQUIP(NEXT_CAL_DT);

CREATE INDEX IDX_QC_CAL_HIS_01 ON QC_CALIBRATION_HIS(MEASURE_EQUIP_CD, CAL_DT);
